# cargo

# [[file:~/Workspace/Programming/gosh-rs/adaptor/adaptors.note::*cargo][cargo:1]]
[package]
name = "gosh-adaptor"
version = "0.0.5"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]
description = "Adaptor for chemical model"
homepage = "https://github.com/gosh-rs/gosh-adaptor"
repository = "https://github.com/gosh-rs/gosh-adaptor"
license = "MIT OR Apache-2.0"
exclude = ["bin/*", "docs/*", "lib/*"]

[dependencies]
nom = "5"
structopt = "0.3"
gosh-core = { version=">=0.0.2" }
gosh-model = { version=">=0.0.9" }

[dev-dependencies]
approx = "0.3"

[features]
adhoc = [] # for adhoc hacking
# cargo:1 ends here
