# cargo

# [[file:~/Workspace/Programming/gosh-rs/adaptors/adaptors.note::*cargo][cargo:1]]
[package]
name = "gosh-adaptors"
version = "0.0.3"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
nom = "5"
gosh-core = { git = "https://github.com/gosh-rs/gosh-core.git" }
gosh-models = { git = "https://github.com/gosh-rs/gosh-models.git", features = ["adhoc"] }
# gosh-models = {path = "../models", features = ["adhoc"]}
# text-parser = { path = "../../gchemol-rs/parser" }
structopt = "0.3"

[dev-dependencies]
# cargo:1 ends here
