# cargo

# [[file:~/Workspace/Programming/gosh-rs/adaptors/adaptors.note::*cargo][cargo:1]]
[package]
name = "gosh-adaptor"
version = "0.0.4"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
nom = "5"
structopt = "0.3"
gosh-core = { version="0.0.1", path = "../core" }
gosh-model = { version="0.0.8", path = "../models", features = ["adhoc"]}

[dev-dependencies]
approx = "0.3"
# cargo:1 ends here
